# Scenario base: autenticazione a 2 fattori (2FA) - Caso base con distribuzioni esponenziali
name: "2FA (base)"
arrival_process: "exp"
service_dist:
    A: "exp"
    B: "exp"
    P: "exp"
interarrival_mean_s: 3.0
heavy_load: false
service_demands:
  A:
    Class1: 0.2
    Class2: 0.4
    Class3: 0.15      # ↑ vs 1FA
  B:
    Class1: 0.8
    Class2: 0.0
    Class3: 0.0
  P:
    Class1: 0.0
    Class2: 0.7       # ↑ vs 1FA
    Class3: 0.0
