name: "1FA (dist)"
arrival_process: "exp"
service_dist:
    A: "erlang"
    B: "lognorm"
    P: "erlang"
interarrival_mean_s: 3.0
heavy_load: false
service_demands:
  A:
    Class1: 0.2
    Class2: 0.4
    Class3: 0.1
  B:
    Class1: 0.8
    Class2: 0.0
    Class3: 0.0
  P:
    Class1: 0.0
    Class2: 0.4
    Class3: 0.0
